# Generated by Django 4.2 on 2025-10-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
