# Generated by Django 4.2 on 2025-10-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_persona_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='user',
        ),
    ]
