# Generated by Django 4.2 on 2025-10-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='primer_ingreso',
            field=models.BooleanField(default=True),
        ),
    ]
