# Generated by Django 4.2 on 2025-10-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_primer_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotas',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
    ]
