# Generated by Django 4.2 on 2025-11-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_persona_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='puede_adoptar',
            field=models.BooleanField(default=False),
        ),
    ]
