# Generated by Django 4.2 on 2025-11-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mascotas_fotos'),
        ('core', '0008_persona_puede_adoptar'),
    ]

    operations = [
    ]
