# Generated by Django 4.2 on 2025-11-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_0007_mascotas_fotos_0008_persona_puede_adoptar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='primer_ingreso',
            field=models.BooleanField(default=False),
        ),
    ]
