# Generated by Django 4.2 on 2025-12-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_novedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='solicitud',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.solicitudadopcion'),
        ),
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='estado',
            field=models.CharField(choices=[('iniciada', 'Iniciada'), ('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
