# Generated by Django 4.2 on 2025-12-11 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_adopcion_solicitud_alter_solicitudadopcion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotas',
            name='estado_inicial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='VacunasSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(max_length=100)),
                ('fecha_puesta', models.DateField(auto_now_add=True)),
                ('fecha_prox_dosis', models.DateField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mascotas')),
            ],
        ),
        migrations.CreateModel(
            name='ObservacionesSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('detalle', models.TextField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mascotas')),
            ],
        ),
    ]
