# Generated by Django 4.2 on 2025-12-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_mascotas_estado_inicial_vacunasseguimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacunasseguimiento',
            old_name='fecha_prox_dosis',
            new_name='proxima_dosis',
        ),
    ]
